server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never

spring:
  datasource:
    url: 'jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:projectx}'
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: ${SEC_NAME:root}
      password: ${SEC_PASSWORD:root}
      roles: admin
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

projectx:
  app:
    jwtSecret: ${JWT_SECRET:secretKey}
    jwtExpirationMs: ${JWT_EXPIRE_MS:3600000}